name: Run Hello Action
on: push

jobs:
    hello: 
        runs-on: ubuntu-latest
        name: Hello
        steps:
            - name: Hello
              uses: wafuwafu13/GitHub-Actions-Introduction-to-Practice@v1.0.0